---
openapi: 3.0.0
info:
  title: retr
  description: ret
  version: rte
servers:
- url: https://virtserver.swaggerhub.com/andresoares13/rtretert/rte
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
